server:
  servlet:
    context-path: /admin
spring:
  application:
    name: MerryCodes
  #    MySQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merrycodes?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    #    Druid 数据库连接池配置
    druid:
      # 连接池的最大值
      max-active: 20
      # 连接池启动时的初始值
      initial-size: 1
      # 最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
      max-wait: 60000
      # 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 1
      filters: stat,wall
      time-between-eviction-runs-millis: 60000
      # 连接的超时时间，默认为半小时
      min-evictable-idle-time-millis: 300000
      # 检查连接是否有效
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
# log
logging:
  level:
    com.merrycodes.mapper: trace
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml