spring:
  #    MySQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merrycodes?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  #    Redis（连接池使用默认配置）
  redis:
    #    Redis数据库索引
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 3000