spring:
  #    MySQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merrycodes?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  #    Redis（连接池使用默认配置）
  redis:
    #    Redis数据库索引
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 3000
jwt:
  auth-login-url: /admin/auth/login
  auth-logout-url: /admin/auth/logout
  public-key-path: D:\MerryCodes\rsa_key.pub
  private-key-path: D:\MerryCodes\rsa_key
  jwt-payload-user-key: user
  #  没有选择 '记住我' 24 * 60 一天
  expiration: 1440
  #  选择 '记住我' 24 * 60 * 7 一周
  expiration-remember: 10080
